name: app_data_state
description: "A new Flutter package to handle state inside apps"
version: 0.0.3
homepage: https://github.com/muhammadmateen027/data_state

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.dataState
        pluginClass: DataState
      ios:
        pluginClass: DataState
