name: Publish to pub.dev

on:
  push:
    tags:
      # must align with the tag-pattern configured on pub.dev, often just replace
      # {{version}} with [0-9]+.[0-9]+.[0-9]+
      - '[0-9]+.[0-9]+.[0-9]+'
      # tag-pattern on pub.dev: 'v{{version}}'
      # If you prefer tags like '1.2.3', without the 'v' prefix, then use:
      # - '[0-9]+.[0-9]+.[0-9]+' # tag-pattern on pub.dev: '{{version}}'
      # If your repository contains multiple packages consider a pattern like:
      # - 'my_package_name-v[0-9]+.[0-9]+.[0-9]+'

# Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
          channel: 'stable'
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: flutter pub get
      # Here you can insert custom steps you need
      # - run: dart tool/generate-code.dart
      - name: Publish
        run: flutter pub publish --force


#  git tag VERSION => git tag 0.0.3
#  git push origin VERSION => git push origin 0.0.3